#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @import console/error
# @import path/absolutePath
# @import path/relativePath
# @import terraform/terraform

terraformFmt () {
    local module    
    local short

    module="$(absolutePath "${1}")"
    short="$(relativePath "${module}" "${MANAGE_REPOSITORY}")"

    [[ -d "${module}" ]] || {
        error "${short}: No such file or directory"

        return 1
    }

    (
        cd "${module}" || return 1

        terraform fmt -write=true "${module}"  &> /dev/null || return 1
    ) || {
        error "${short}: failed to validate"

        return 1
    }
}
