#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @import console/error
# @import path/absolutePath
# @import path/relativePath
# @import lang/truth
# @import terraform/terraform


terraformInit () {
    local module    
    local short
    local clean

    module="$(absolutePath "${1}")"
    short="$(relativePath "${module}" "${MANAGE_REPOSITORY}")"
    clean="${2:-false}"

    [[ -d "${module}" ]] || {
        error "${short}: No such file or directory"

        return 1
    }

    (
        cd "${module}" || return 1

        if truth "${clean}"
        then
            rm -rf "${module}/terraform.tfstate" "${module}/terraform.tfstate.backup" "${module}/.terraform" || true
        fi

        {
            terraform init \
            -force-copy \
            -get=true \
            -get-plugins=true \
            -input=false &> /dev/null 
        } || return 1
    ) || {
        error "${short}: failed to initialize"

        return 1
    }
}
