#!/usr/bin/env bash
# @import console/error

function architecture () {
    local arch

    arch=$(uname -m)

    case "${arch}" in
        x86_64|amd64)
            arch="amd64"
            ;;
        aarch64)
            arch="arm64"
            ;;
        arm64)
            arch="arm64"
            ;;
        *)
            error "Unknown architecture: $(uname -m)"
            return 1
    esac

    echo ${arch}
}
