#!/usr/bin/env bash
# @import console/error

function conventionalArchitecture () {
    local arch

    arch=$(uname -m)

    case "${arch}" in
        x86_64|amd64)
            arch="amd64"
            ;;
        i?86|x86)
            arch="386"
            ;;
        arm*)
            arch="arm"
            ;;
        aarch64)
            arch="arm64"
            ;;
        *)
            error "Unknown architecture: $(uname -m)"
            return 1
    esac

    echo ${arch}
}
