#!/usr/bin/env bash
# @import console/error

function conventionalArchitecture () {
    local arch

    arch=$(uname -m)

    case "${arch}" in
        # armv6*)
        #     arch="arm"
        #     ;;
        x86_64)
            arch="amd64"
            ;;
        x86)
            arch="386"
            ;;
        i686)
            arch="386"
            ;;
        i386)
            arch="386"
            ;;
        aarch64)
            arch="arm64"
            ;;
        armv7*)
            arch="arm"
            ;;
        *)
            error "Unknown architecture: $(uname -m)"
            return 1
    esac

    echo ${arch}
}
