#!/usr/bin/env bash
# @import console/die
# @import lang/exists
# @import stack-tools/stackToolsDefaults

downloadGosu ()
{
    verbose true
    strict true

    exists gpg || die "Cannot find 'gpg' in path."
    exists curl || die "Cannot find 'gpg' in path."

    stackToolsDefaults

    {
        gpg --batch --keyserver ha.pool.sks-keyservers.net \
            --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 &> /dev/null
    } || die "Cannot import tianon GPG key"

    [ -z "${GOSU_BINARY}" ] && die "'GOSU_BINARY' is not defined"
    [ -z "${GOSU_BINARY_SIGNATURE}" ] && die "'GOSU_BINARY_SIGNATURE' is not defined"
    [ -z "${GOSU_SHA256SUMS}" ] && die "'GOSU_SHA256SUMS' is not defined"
    [ -z "${GOSU_SHA256SUMS_SIGNATURE}" ] && die "'GOSU_SHA256SUMS_SIGNATURE' is not defined"

    [ -z "${GOSU_DIRECTORY}" ] && GOSU_DIRECTORY="${MANAGE_REPOSITORY}/vendor/gosu"

    if [ ! -f "${GOSU_DIRECTORY}/gosu" ]
    then
        mkdir -p "${GOSU_DIRECTORY}"
        curl -0 -S -L --progress-bar "${GOSU_BINARY}" -o "${GOSU_DIRECTORY}/${GOSU_BINARY##*/}"
        curl -0 -s -S -L "${GOSU_BINARY_SIGNATURE}" -o "${GOSU_DIRECTORY}/${GOSU_BINARY_SIGNATURE##*/}"
        curl -0 -s -S -L "${GOSU_SHA256SUMS}" -o "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}"
        curl -0 -s -S -L "${GOSU_SHA256SUMS_SIGNATURE}" -o "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS_SIGNATURE##*/}"

        {
            gpg --batch --verify "${GOSU_DIRECTORY}/${GOSU_BINARY_SIGNATURE##*/}" \
                "${GOSU_DIRECTORY}/${GOSU_BINARY##*/}" &> /dev/null
        } || die "Cannot verify '${GOSU_BINARY##*/}'"

        {
            gpg --batch --verify "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS_SIGNATURE##*/}" \
                "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}" &> /dev/null
        } || die "Cannot verify '${GOSU_SHA256SUMS##*/}'"

        local SHA256SUM
        SHA256SUM="$(grep "${GOSU_BINARY##*/}" "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}")"
        echo "${SHA256SUM}" > "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}"

        (
            cd "${GOSU_DIRECTORY}" || die
            sha256sum --status -c "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}"
        )

        rm -f "${GOSU_DIRECTORY}/${GOSU_BINARY_SIGNATURE##*/}" \
            "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS##*/}" \
            "${GOSU_DIRECTORY}/${GOSU_SHA256SUMS_SIGNATURE##*/}"

        mv "${GOSU_DIRECTORY}/${GOSU_BINARY##*/}" "${GOSU_DIRECTORY}/gosu"
        chmod +x "${GOSU_DIRECTORY}/gosu"
    fi
}
