#!/usr/bin/env bash
# @import console/info
# @import console/error
# @import console/die
# @import docker/checkSha
# @import lang/exists

downloadGosu ()
{
    exists curl || die "Cannot find 'curl' in path"

    local gosuTarget="${GOSU_TARGET:-${MANAGE_REPOSITORY}/vendor/gosu/gosu}"
    local gosuSha256="${GOSU_SHA256:-347d0294d73c991c08408599bd21e241cc994947d1c43cd99cf49cfb783c89fd}"
    local gosuUrl="${GOSU_URL:-https://github.com/epiloque/docker-base/releases/download/v1.0.3/gosu-amd64}"
    local dumb_init_sha

    if [ ! -f "${gosuTarget}" ]
    then
        mkdir -p "$(dirname "${gosuTarget}")"
        curl -s -S -L --progress-bar "${gosuUrl}" -o "${gosuTarget}"
    fi

    dumb_init_sha="$(checkSha "${gosuTarget}")"

    if [[ "${gosuSha256}" != "${dumb_init_sha}" ]]
    then
        rm "${gosuTarget}"
        die 'gosu SHA256SUM did not match'
    fi
}
