#!/usr/bin/env bash
# @import console/die
# @import lang/exists
# @import download/downloadDefaults
# @import manage/trust

downloadRclone ()
{
    verbose true
    strict true

    exists curl || die "Cannot find 'curl' in path."
    exists unzip || die "Cannot find 'unzip' in path."

    downloadDefaults

    [ -z "${RCLONE_BINARY}" ] && die "'RCLONE_BINARY' is not defined"

    [ -z "${RCLONE_DIRECTORY}" ] && RCLONE_DIRECTORY="${DOWNLOAD_DIRECTORY}/rclone"

    if [ ! -f "${RCLONE_DIRECTORY}/rclone" ]
    then
        mkdir -p "${RCLONE_DIRECTORY}"
        curl -0 -S -L --progress-bar "${RCLONE_BINARY}" -o "${RCLONE_DIRECTORY}/${RCLONE_BINARY##*/}"

        unzip -j -qq "${RCLONE_DIRECTORY}/${RCLONE_BINARY##*/}" '*/rclone' -d "${RCLONE_DIRECTORY}"
        rm -f "${RCLONE_DIRECTORY}/${RCLONE_BINARY##*/}"

        chmod +x "${RCLONE_DIRECTORY}/rclone"
    fi
}
