#!/usr/bin/env bash
# shellcheck disable=SC2034
# @import console/die
# @import generic/architecture
# @import generic/OSType

function downloadDefaults () {
    local arch
    local arch
    local ostype
    local osxOSType

    arch="$(architecture)" || die "Unsupported architecture"
    ostype="$(OSType)" || die "Unsupported OS"

    osxOSType="${ostype}"

    if [[ "${osxOSType}" == "darwin" ]]
    then
        osxOSType="osx"
    fi


    HASHICORP_GPG_KEY="${HASHICORP_GPG_KEY:-C874011F0AB405110D02105534365D9472D7468F}"

    DOWNLOAD_DIRECTORY="${MANAGE_REPOSITORY}/vendor"

    GOMPLATE_VERSION="${GOMPLATE_VERSION:-3.11.3}"
    GOMPLATE_BINARY="${GOMPLATE_BINARY:-https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/gomplate_${ostype}-${arch}-slim}"
    GOMPLATE_SHA256SUMS="${GOMPLATE_SHA256SUMS:-https://github.com/hairyhenderson/gomplate/releases/download/v${GOMPLATE_VERSION}/checksums-v${GOMPLATE_VERSION}_sha256.txt}"

    HYPERFINE_VERSION="${HYPERFINE_VERSION:-1.15.0}"

    TINI_VERSION="${TINI_VERSION:-0.19.0}"
    TINI_BINARY="${TINI_BINARY:-https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-${arch}}"
    TINI_BINARY_SIGNATURE="${TINI_SHA256SUMS_SIGNATURE:-https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini-${arch}.asc}"

    GOSU_VERSION="${GOSU_VERSION:-1.14}"
    GOSU_BINARY="${GOSU_BINARY:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${arch}}"
    GOSU_BINARY_SIGNATURE="${GOSU_BINARY_SIGNATURE:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${arch}.asc}"
    GOSU_SHA256SUMS="${GOSU_SHA256SUMS:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/SHA256SUMS}"
    GOSU_SHA256SUMS_SIGNATURE="${GOSU_SHA256SUMS_SIGNATURE:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/SHA256SUMS.asc}"

    TERRAFORM_VERSION="${TERRAFORM_VERSION:-1.3.4}"
    TERRAFORM_BINARY="${TERRAFORM_BINARY:-https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_${ostype}_${arch}.zip}"
    TERRAFORM_SHA256SUMS="${TERRAFORM_SHA256SUMS:-https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS}"
    TERRAFORM_SHA256SUMS_SIGNATURE="${TERRAFORM_SHA256SUMS_SIGNATURE:-https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig}"

    TFLINT_VERSION="${TFLINT_VERSION:-0.42.2}"
    TFLINT_BINARY="https://github.com/terraform-linters/tflint/releases/download/v${TFLINT_VERSION}/tflint_${ostype}_${arch}.zip"

    PACKER_VERSION="${PACKER_VERSION:-1.8.4}"
    PACKER_BINARY="${PACKER_BINARY:-https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_${ostype}_${arch}.zip}"
    PACKER_SHA256SUMS="${PACKER_SHA256SUMS:-https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS}"
    PACKER_SHA256SUMS_SIGNATURE="${PACKER_SHA256SUMS_SIGNATURE:-https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS.sig}"

    RESTIC_VERSION="${RESTIC_VERSION:-0.14.0}"
    RESTIC_BINARY="${RESTIC_BINARY:-https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_${ostype}_${arch}.bz2}"
    RESTIC_SHA256SUMS="${RESTIC_SHA256SUMS:-https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/SHA256SUMS}"
    RESTIC_SHA256SUMS_SIGNATURE="${RESTIC_SHA256SUMS_SIGNATURE:-https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/SHA256SUMS.asc}"

    RCLONE_VERSION="${RCLONE_VERSION:-1.60.0}"
    RCLONE_BINARY="${RCLONE_BINARY:-https://downloads.rclone.org/v${RCLONE_VERSION}/rclone-v${RCLONE_VERSION}-${osxOSType}-${arch}.zip}"
}
