#!/usr/bin/env bash
# shellcheck disable=SC2034
# @import console/die
# @import generic/conventionalArchitecture
# @import generic/goArchitecture

function stackToolsDefaults () {
    local arch
    local garch

    arch="$(conventionalArchitecture)" || die "Unsupported architecture"
    garch="$(goArchitecture)" || die "Unsupported architecture"

    TINI_VERSION="${TINI_VERSION:-v0.18.0}"
    TINI_BINARY="${TINI_BINARY:-https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${garch}}"
    TINI_BINARY_SIGNATURE="${TINI_SHA256SUMS_SIGNATURE:-https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini-${garch}.asc}"

    GOSU_VERSION="${GOSU_VERSION:-1.10}"
    GOSU_BINARY="${GOSU_BINARY:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${garch}}"
    GOSU_BINARY_SIGNATURE="${GOSU_BINARY_SIGNATURE:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-${garch}.asc}"
    GOSU_SHA256SUMS="${GOSU_SHA256SUMS:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/SHA256SUMS}"
    GOSU_SHA256SUMS_SIGNATURE="${GOSU_SHA256SUMS_SIGNATURE:-https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/SHA256SUMS.asc}"

    TERRAFORM_VERSION="${TERRAFORM_VERSION:-0.11.8}"
    TERRAFORM_BINARY="${TERRAFORM_BINARY:-https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_${arch}.zip}"
    TERRAFORM_SHA256SUMS="${TERRAFORM_SHA256SUMS:-https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS}"
    TERRAFORM_SHA256SUMS_SIGNATURE="${TERRAFORM_SHA256SUMS_SIGNATURE:-https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_SHA256SUMS.sig}"

    PACKER_VERSION="${PACKER_VERSION:-1.3.1}"
    PACKER_BINARY="${PACKER_BINARY:-https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_${arch}.zip}"
    PACKER_SHA256SUMS="${PACKER_SHA256SUMS:-https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS}"
    PACKER_SHA256SUMS_SIGNATURE="${PACKER_SHA256SUMS_SIGNATURE:-https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_SHA256SUMS.sig}"

    RESTIC_VERSION="${RESTIC_VERSION:-0.9.2}"
    RESTIC_BINARY="${RESTIC_BINARY:-https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_linux_${arch}.bz2}"
    RESTIC_SHA256SUMS="${RESTIC_SHA256SUMS:-https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/SHA256SUMS}"
    RESTIC_SHA256SUMS_SIGNATURE="${RESTIC_SHA256SUMS_SIGNATURE:-https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/SHA256SUMS.asc}"
}
