#!/usr/bin/env bash
# @import console/die
# @import lang/exists
# @import stack-tools/stackToolsDefaults

downloadPacker ()
{
    verbose true
    strict true

    exists gpg || die "Cannot find 'gpg' in path."
    exists curl || die "Cannot find 'gpg' in path."
    exists unzip || die "Cannot find 'unzip' in path."

    stackToolsDefaults

    {
        gpg --batch --keyserver ha.pool.sks-keyservers.net \
            --recv-keys 91A6E7F85D05C65630BEF18951852D87348FFC4C &> /dev/null
    } || die "Cannot import HashiCorp GPG key"

    [ -z "${PACKER_BINARY}" ] && die "'PACKER_BINARY' is not defined"
    [ -z "${PACKER_SHA256SUMS}" ] && die "'PACKER_SHA256SUMS' is not defined"
    [ -z "${PACKER_SHA256SUMS_SIGNATURE}" ] && die "'PACKER_SHA256SUMS_SIGNATURE' is not defined"

    [ -z "${PACKER_DIRECTORY}" ] && PACKER_DIRECTORY="${MANAGE_REPOSITORY}/vendor/packer"

    if [ ! -f "${PACKER_DIRECTORY}/packer" ]
    then
        mkdir -p "${PACKER_DIRECTORY}"
        curl -0 -S -L --progress-bar "${PACKER_BINARY}" -o "${PACKER_DIRECTORY}/${PACKER_BINARY##*/}"
        curl -0 -s -S -L "${PACKER_SHA256SUMS}" -o "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS##*/}"
        curl -0 -s -S -L "${PACKER_SHA256SUMS_SIGNATURE}" -o "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS_SIGNATURE##*/}"

        {
            gpg --batch --verify "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS_SIGNATURE##*/}" \
                "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS##*/}" &> /dev/null
        } || die "Cannot verify '${PACKER_SHA256SUMS##*/}'"

        local SHA256SUM
        SHA256SUM="$(grep "${PACKER_BINARY##*/}" "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS##*/}")"
        echo "${SHA256SUM}" > "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS##*/}"

        (
            cd "${PACKER_DIRECTORY}" || die
            sha256sum --status -c "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS##*/}"
        )

        unzip -qq "${PACKER_DIRECTORY}/${PACKER_BINARY##*/}" -d "${PACKER_DIRECTORY}"
        rm -f "${PACKER_DIRECTORY}/${PACKER_BINARY##*/}" \
            "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS##*/}" \
            "${PACKER_DIRECTORY}/${PACKER_SHA256SUMS_SIGNATURE##*/}"

        chmod +x "${PACKER_DIRECTORY}/packer"
    fi
}
