#!/usr/bin/env bash
# @import console/die
# @import lang/exists
# @import stack-tools/stackToolsDefaults
# @import manage/trust

downloadTerraform ()
{
    verbose true
    strict true

    exists gpg || die "Cannot find 'gpg' in path."
    exists curl || die "Cannot find 'curl' in path."
    exists unzip || die "Cannot find 'unzip' in path."

    stackToolsDefaults

    trust 91A6E7F85D05C65630BEF18951852D87348FFC4C || die "Cannot import HashiCorp GPG key"

    [ -z "${TERRAFORM_BINARY}" ] && die "'TERRAFORM_BINARY' is not defined"
    [ -z "${TERRAFORM_SHA256SUMS}" ] && die "'TERRAFORM_SHA256SUMS' is not defined"
    [ -z "${TERRAFORM_SHA256SUMS_SIGNATURE}" ] && die "'TERRAFORM_SHA256SUMS_SIGNATURE' is not defined"

    [ -z "${TERRAFORM_DIRECTORY}" ] && TERRAFORM_DIRECTORY="${MANAGE_REPOSITORY}/vendor/terraform"

    if [ ! -f "${TERRAFORM_DIRECTORY}/terraform" ]
    then
        mkdir -p "${TERRAFORM_DIRECTORY}"
        curl -0 -S -L --progress-bar "${TERRAFORM_BINARY}" -o "${TERRAFORM_DIRECTORY}/${TERRAFORM_BINARY##*/}"
        curl -0 -s -S -L "${TERRAFORM_SHA256SUMS}" -o "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS##*/}"
        curl -0 -s -S -L "${TERRAFORM_SHA256SUMS_SIGNATURE}" -o "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS_SIGNATURE##*/}"

        {
            gpg --batch --verify "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS_SIGNATURE##*/}" \
                "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS##*/}" &> /dev/null
        } || die "Cannot verify '${TERRAFORM_SHA256SUMS##*/}'"

        local SHA256SUM
        SHA256SUM="$(grep "${TERRAFORM_BINARY##*/}" "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS##*/}")"
        echo "${SHA256SUM}" > "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS##*/}"

        (
            cd "${TERRAFORM_DIRECTORY}" || die
            sha256sum --status -c "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS##*/}"
        )

        unzip -qq "${TERRAFORM_DIRECTORY}/${TERRAFORM_BINARY##*/}" -d "${TERRAFORM_DIRECTORY}"
        rm -f "${TERRAFORM_DIRECTORY}/${TERRAFORM_BINARY##*/}" \
            "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS##*/}" \
            "${TERRAFORM_DIRECTORY}/${TERRAFORM_SHA256SUMS_SIGNATURE##*/}"

        chmod +x "${TERRAFORM_DIRECTORY}/terraform"
    fi
}
