#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# <doc>
#
# docker-base
#
# </doc>
#
# <import>
#
# collection-shell
# collection-message
# collection-string
#
# </import>

main ()
{
    verbose true
    strict true

    case "$(uname -m)" in
        x86_64)
            ARCH=x86_64
            ;;
        armv7l)
            ARCH=armhf
            ;;
        i?86)
            ARCH=i386
            ;;
    esac

    echo "${ARCH}"
}
