#!/usr/bin/env bash
# @description build gosu (Go-based setuid+setgid+setgroups+exec)
# @import console/die
# @dependency docker
# @dependency sha256sum

main ()
{
    verbose true
    strict true

    cd "${MANAGE_REPOSITORY}/vendor/gosu" || _ die
    mkdir -p "${MANAGE_REPOSITORY}/release/gosu"

    docker build --pull -t gosu .
    rm -f gosu* SHA256SUMS*
    docker run --rm gosu sh -c 'cd /go/bin && tar -c gosu*' | tar -xv
    sha256sum gosu* > SHA256SUMS

    cp -rf gosu* "${MANAGE_REPOSITORY}/release/gosu"
    cp -rf SHA256SUMS* "${MANAGE_REPOSITORY}/release/gosu"
}
