#!/usr/bin/env bash
# @description build dumb-init minimal init system for Linux containers
# @import docker/dockerBuild
# @import console/die
# @import console/info
# @dependency docker
# @dependency sha256sum

main ()
{
    verbose true
    strict true
    local scope="${DOCKER_SCOPE:-internal}"

    _ info "Building dumb-init docker image"

    # _ dockerBuild dumb-init

    if [[ -d "${MANAGE_REPOSITORY}/release/dumb-init" ]]
    then
        rm -rf "${MANAGE_REPOSITORY}/release/dumb-init"
    fi

    mkdir -p "${MANAGE_REPOSITORY}/release/dumb-init"

    _ info "Copying dumb-init binary"

    docker run -it \
        -u "$(id -u)" \
        -v "${MANAGE_REPOSITORY}/release/dumb-init":/copy \
        "${scope}"/dumb-init:latest cp dumb-init /copy/dumb-init-x86_64

    (
        cd "${MANAGE_REPOSITORY}/release/dumb-init" || _ die
        sha256sum dumb* > SHA256SUMS
    )
}

