#!/usr/bin/env bash
# @description test stack-tools modules
# @import download/downloadGosu
# @import download/downloadHyperfine
# @import download/downloadPacker
# @import download/downloadRclone
# @import download/downloadRestic
# @import download/downloadTerraform
# @import download/downloadTflint
# @import download/downloadTini
# @import download/downloadGomplate
# @import console/info

main ()
{
    verbose true
    strict true
    local code=0

    rm -rf \
        "${MANAGE_REPOSITORY:?}/vendor/tini" \
        "${MANAGE_REPOSITORY:?}/vendor/gosu" \
        "${MANAGE_REPOSITORY:?}/vendor/packer" \
        "${MANAGE_REPOSITORY:?}/vendor/terraform" \
        "${MANAGE_REPOSITORY:?}/vendor/restic" \
        "${MANAGE_REPOSITORY:?}/vendor/hyperfine" \
        "${MANAGE_REPOSITORY:?}/vendor/rclone" \
        "${MANAGE_REPOSITORY:?}/vendor/tflint" \
        "${MANAGE_REPOSITORY:?}/vendor/gomplate"

    _ info "Downloading tini ..."
    _ downloadTini || ((exitCode++))
    _ info "Downloading gosu ..."
    _ downloadGosu || ((exitCode++))
    _ info "Downloading packer ..."
    _ downloadPacker || ((exitCode++))
    _ info "Downloading terraform ..."
    _ downloadTerraform || ((exitCode++))
    _ info "Downloading restic ..."
    _ downloadRestic || ((exitCode++))
    _ info "Downloading hyperfine..."
    _ downloadHyperfine || ((exitCode++))
    _ info "Downloading rclone..."
    _ downloadRclone || ((exitCode++))
    _ info "Downloading tflint..."
    _ downloadTflint || ((exitCode++))
    _ info "Downloading gomplate..."
    _ downloadGomplate || ((exitCode++))

    exit "${code}"
}
