#!/usr/bin/env bash
# @import sharkdp/downloadHyperfine

hyperfine () {
    [ -z "${HYPERFINE_DIRECTORY}" ] &&
        HYPERFINE_DIRECTORY="${MANAGE_REPOSITORY}/vendor/hyperfine"

    downloadHyperfine

    "${HYPERFINE_DIRECTORY}/hyperfine" "$@"
}
