name: test
on:
  push:
    branches:
      - trunk
    tags:
      - 'v*.*.*'
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  reelase:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run: |
          ./manage trust-escapace
          ./manage test
