#!/usr/bin/env bash

npmIsPrivate () {
    local json="$1"
    local private

    private="$(jq -r '.private // empty' < "${json}")"

    if [[ "true" == "${private}" ]]
    then
        # Return 0 if private
        return 0
    else
        # Return 1 if not private
        return 1
    fi
}
