#!/usr/bin/env bash

npmShouldPublish () {
    local name="$1"
    local version="$2"

    # Return 0 if package doesnt exists
    npm info "${name}" &> /dev/null || return 0

    if [[ "$(npm info "${name}@${version}" ".version")" == "${version}" ]]
    then
        # Return 1 if package and version exists
        return 1
    else
        # Return 0 if package exists but version does not
        return 0
    fi
}
