#!/usr/bin/env bash
#
# vim: set ft=sh:
#
# @import console/error
# @import console/info
# @import lang/exists
# @import lang/required
# @import lang/truth
# @import stack/stackAmazonEBS
# @import stack/stackVagrant
# @import path/absolutePath
# @import packer/packer

stackPacker () {
    local directory
    local template="$(absolutePath "${1}")"
    local type="${2}"
    local clean="${3:-true}"

    if _ required "${STACK_CLEAN}"
    then
        clean="${STACK_CLEAN}"
    fi

    exists jq || {
        error "stackPacker: Cannot find jq"

        return 1
    }

    required "${template}" "${type}" "${clean}" || {
        error "stackPacker: ReferenceError - attempt is being made to access a variable that is not defined"

        return 1
    }

    [[ -f "${template}" ]] || {
        error "stackPacker: No such file or directory"

        return 1
    }

    directory="$(dirname "${template}")"

    cd "${directory}" || return 1

    packer validate "${template}" || return 1

    case "${type}" in
        amazon-ebs)
            stackAmazonEBS "${template}" "${clean}"
            ;;
        virtualbox-iso)
            stackVagrant "${template}" "${type}" "${clean}"
            ;;
        vmware-iso)
            stackVagrant "${template}" "${type}" "${clean}"
            ;;
        hyperv-iso)
            stackVagrant "${template}" "${type}" "${clean}"
            ;;
        qemu)
            stackVagrant "${template}" "${type}" "${clean}"
            ;;
        *)
            error "stackPacker: Unsupported builder type '${type}'"

            return 1
    esac
}
